spring.application.name: "externalRestDemo"


cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

spring:
  r2dbc:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
    pool:
      initial-size: 10
      max-size: 24
      max-idle-time: 30000ms

logging:
  level:
    org.springframework.r2dbc.core: debug


openai:
  base-url: "https://api.openai.com/v1"
  api-key: ${OPENAI_API_KEY}
  org-id: ${OPENAI_ORG_ID}
  project: ${OPENAI_PROJECT_ID}
